### ISSUE TITLE
Joomla 3.4.3 Javascript problem

### ISSUE THREAD

**Issue by sergueikp** [ghazal/mod_multijscss#1]
Hi Ghazal,
I'm using Taxi Booking component on my site, and there is a Google maps displaying problem in this component, the map is not fully loaded, 
but when I deactivate your module Google maps is loaded well,
can you help me please to configure your component to resolve this issue ?

Here is the link to the problem page on my site: http://aramis-paris.com/taxi-cab-shuttles-airports-paris-france-booking?lang=en

Best regards.
Serguei.

**Comment by ghazal** [comment]
Hi,
you closed this issue but I  checked your site anyway. No wonder there are issues.
The component TaxiBooking is loading jQuery itself (and and older version that the one used by joomla), which is bad.
You should not use JCHOptimize before finishing your site.
Why on earth is Google Analytics script located in head ?
My little module does nothing else but send JS and CSS in the head.
Regards,
ghazal

**Comment by sergueikp** [comment]
Hi, Ghazal, thank you for your answer, yesterday at night I found the reason of the problem, it was a bad css code in my customer.css file.

Seguei. 

De : ghazal [mailto:notifications@github.com] 
Envoyé : jeudi 22 octobre 2015 10:00
À : ghazal/mod_multijscss
Cc : sergueikp
Objet : Re: [mod_multijscss] Joomla 3.4.3 Javascript problem (#1)

Hi,
you closed this issue but I checked your site anyway. No wonder there are issues.
The component TaxiBooking is loading jQuery itself (and and older version that the one used by joomla), which is bad.
You should not use JCHOptimize before finishing your site.
Why on earth is Google Analytics script located in head ?
My little module does nothing else but send JS and CSS in the head.
Regards,
ghazal
